version: "3"

# sudo docker-compose build
# sudo docker-compose up -d
# sudo docker-compose exec bio sh

services:
  bio:
    build: java
    container_name: bioformat
    volumes:
        - ./python:/app
    tty: true
